//////////////////////////////////////////////////////
// Copyright (C) Microsoft. 2018. All rights reserved.
//////////////////////////////////////////////////////


// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogGameShift, Log, All);

namespace GameShift
{
	enum class EVerbMode
	{
		GET,
		POST,
		PUT,
		DELETE
	};
	const FString& GetVerbString(EVerbMode Mode);
};